server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8861/eureka/,http://peer2:8961/eureka/
  instance:
    hostname: peer1
spring:
  profiles: peer1
  application:
    name: eureka-server

---
server:
  port: 8861
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8961/eureka/
  instance:
    hostname: peer2
spring:
  profiles: peer2
  application:
    name: eureka-server

---
server:
  port: 8961
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8861/eureka/
  instance:
    hostname: peer3
spring:
  profiles: peer3
  application:
    name: eureka-server